spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
zuul:
  # 全部服务忽略敏感头(全部服务都可以传递cookie)
  sensitive-headers: 
  routes:
    aaa:
      path: /myProduct/**
      serviceId: product
      sensitiveHeaders:
    #简洁写法
#    product: /myProduct/**
  ignored-patterns:
    - /**/product/listForOrder
management:
  endpoints:
    web:
      exposure:
        include: "*"
