spring:
  datasource:
    name: product-datasource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.205:3306/spring_cloud_sell?useUnicode=true&allowMultiQueries=true&useSSL=false
    username: root
    password: fxl421125
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
env: dev    
